INSERT INTO categoria (Nome) VALUES
('Cani'),
('Gatti'),
('Cavalli'),
('Conigli'),
('Uccelli'),
('Pesci e Tartarughe');

INSERT INTO prodotto (Nome, Descrizione, Disponibilita, Prezzo, ID_Categoria, immagine, mime_type, attivo) VALUES
('Ciotola Gatto Food', 'Ciotola celeste in acciaio inox da 240 ml, con base antiscivolo e simpatica decorazione', 20, 8.90, 2, 'ciotola1.png', 'image/png', 1),
('Ciotola Gatto Doppia', 'Set ciotole in acciaio inox rimovibili e lavabili in lavastoviglie, con supporto a forma di gatto e piedini antiscivolo', 20, 11.50, 2, 'ciotola2.png', 'image/png', 1),
('Ciotola Gatto Ceramica', 'Ciotola rosa in ceramica da 250 ml, robusta e facile da pulire anche in lavastoviglie', 20, 11.90, 2, 'ciotola3.png', 'image/png', 1),
('Collare Gatto con Fiore', 'Collare modello Bloom regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare1.png', 'image/png', 1),
('Collare Gatto con Fragola', 'Collare modello Berry Love regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare2.png', 'image/png', 1),
('Collare Gatto con Avocado', 'Collare modello Avocado regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare3.png', 'image/png', 1),
('Collare Gatto con Caramella', 'Collare modello Gummy Bears regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare4.png', 'image/png', 1),
('Collare Gatto Antiparassitario', 'Collare Seresto antizecche e antipulci con protezione continua fino a 7-8 mesi, inodore e resistente a contatti occasionali con l’acqua', 20, 22.90, 2, 'collare5.png', 'image/png', 1),
('Dentalife Snack Dentale Salmone', 'Snack dentale Purina Dentalife da 40g al gusto salmone, aiuta a ridurre la formazione di tartaro nei gatti adulti grazie alla sua consistenza porosa e croccante', 20, 3.50, 2, 'dentalife1.png', 'image/png', 1),
('Dentalife Snack Dentale Pollo', 'Snack dentale Purina Dentalife da 40g al gusto pollo, aiuta a ridurre la formazione di tartaro nei gatti adulti grazie alla sua consistenza porosa e croccante', 20, 3.50, 2, 'dentalife2.png', 'image/png', 1),
('Felix Le Ghiottonerie Junior', '10 bustine Purina Felix da 85g con teneri bocconcini di manzo e pollo in gelatina, adatto a gattini dai 2 ai 12 mesi per sostenere lo sviluppo di muscoli, ossa e denti sani', 20, 5.90, 2, 'felix1.png', 'image/png', 1),
('Felix Le Ghiottonerie Preferite', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di manzo e pollo oppure salmone e tonno, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix2.png', 'image/png', 1),
('Felix Le Ghiottonerie Varietà', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di platessa e tonno oppure coniglio e pollo, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix3.png', 'image/png', 1),
('Felix Le Ghiottonerie Verdure', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di manzo e carote oppure pollo e pomodoro, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix4.png', 'image/png', 1),
('Gioco Gatto Piume', 'Giocattolo Zolux Ethi’Cat realizzato con materiale riciclato e naturale, ideale per stimolare l’istinto predatorio e favorire l’esercizio fisico del proprio gatto', 20, 2.50, 2, 'gioco1.png', 'image/png', 1),
('Gioco Gatto Laser', 'Giocattolo interattivo Zolux Enjoy Laser per gatti, con un fascio di luce rossa per stimolare l’attività felina e dotato di un pratico portachiavi', 20, 4.90, 2, 'gioco2.png', 'image/png', 1),
('Gioco Gatto Topolino', 'Morbido topolino giocattolo in peluche, dotato di una lunga coda con un pon pon per attirare l’attenzione del proprio gatto grazie anche alla presenza di erba gatta al suo interno', 20, 2.50, 2, 'gioco3.png', 'image/png', 1),
('Guanto Leva Pelo Lovedì', 'Set composto da due guanti con cinturino regolabile e piccoli puntini in silicone che catturano peli, sporco e polvere non solo dal proprio animale ma anche da divani, letti e tappeti', 20, 6.50, 2, 'pulizia1.png', 'image/png', 1),
('Spazzola Lovedì', 'Morbida spazzola per gatti con setole in nylon per lucidare e lisciare tutti i tipi di pelo, dotata di un’impugnatura ergonomica e antiscivolo per una presa confortevole durante la toelettatura', 20, 7.50, 2, 'pulizia2.png', 'image/png', 1),
('Taglia Unghie Lovedì', 'Forbicine per gatti di taglia S con lame in acciaio inossidabile per garantire un taglio netto e preciso, facilitato da una comoda tacca di sicurezza in modo da non accorciare troppo l’unghia', 20, 5.90, 2, 'pulizia3.png', 'image/png', 1),
('Cardatore Lovedì', 'Cardatore per gatti di taglia S con setole in acciaio per districare il sottopelo, rimuovendo i peli morti e prevenendo la formazione di nodi', 20, 7.90, 2, 'pulizia4.png', 'image/png', 1),
('Tiragraffi Torre Multipiano', 'Tiragraffi beige in sisal di misure 103x71x49 cm che comprende una comoda cuccia, una piccola amaca e una pallina in peluche appesa', 20, 39.90, 2, 'tiragraffi1.png', 'image/png', 1),
('Tiragraffi Palo con Labirinto', 'Colonna tiragraffi in robusto sisal di misure 43,5x30 cm, dotata di una base con binari per far scorrere le palline e un pendente in legno appeso con una piuma', 20, 9.90, 2, 'tiragraffi2.png', 'image/png', 1),
('Trasportino Rigido Grigio', 'Trasportino per gatti fino a 8kg in plastica resistente con porta di metallo, conforme agli standard IATA per il trasporto aereo e dotato di una comoda lettiera perfetta per affrontare lunghi viaggi', 20, 32.90, 2, 'trasportino1.png', 'image/png', 1),
('Trasportino Nero con Borsa Imbottita', 'Trasportino in poliestere di dimensioni 29x31x49 cm adatto sia in casa che in viaggio, dotato di cuccia interna estraibile in peluche e varie aperture frontali, laterali e superiori', 20, 35.90, 2, 'trasportino2.png', 'image/png', 1),
('Whiskas Adult Pollo', 'Confezione da 1,4 kg di crocchette Whiskas al pollo per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas1.png', 'image/png', 1),
('Whiskas Junior Pollo', 'Confezione da 1,4 kg di crocchette Whiskas al pollo per gattini in crescita di età compresa tra 2 e 12 mesi, facili da digerire e con nutrienti essenziali per lo sviluppo', 20, 6.60, 2, 'whiskas2.png', 'image/png', 1),
('Whiskas Adult Tonno', 'Confezione da 1,4 kg di crocchette Whiskas al tonno per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas3.png', 'image/png', 1),
('Whiskas Adult Manzo', 'Confezione da 1,4 kg di crocchette Whiskas al manzo per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas4.png', 'image/png', 1);