INSERT INTO categoria (Nome) VALUES
('Cani'),
('Gatti'),
('Cavalli'),
('Conigli'),
('Uccelli'),
('Pesci e Tartarughe');

INSERT INTO prodotto (Nome, Descrizione, Disponibilita, Prezzo, ID_Categoria, immagine, mime_type, attivo) VALUES
('Ciotola Gatto Food', 'Ciotola celeste in acciaio inox da 240 ml, con base antiscivolo e simpatica decorazione', 20, 8.90, 2, 'ciotola1.png', 'image/png', 1),
('Ciotola Gatto Doppia', 'Set ciotole in acciaio inox rimovibili e lavabili in lavastoviglie, con supporto a forma di gatto e piedini antiscivolo', 20, 11.50, 2, 'ciotola2.png', 'image/png', 1),
('Ciotola Gatto Ceramica', 'Ciotola rosa in ceramica da 250 ml, robusta e facile da pulire anche in lavastoviglie', 20, 11.90, 2, 'ciotola3.png', 'image/png', 1),
('Collare Gatto con Fiore', 'Collare modello Bloom regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare1.png', 'image/png', 1),
('Collare Gatto con Fragola', 'Collare modello Berry Love regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare2.png', 'image/png', 1),
('Collare Gatto con Avocado', 'Collare modello Avocado regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare3.png', 'image/png', 1),
('Collare Gatto con Caramella', 'Collare modello Gummy Bears regolabile in nylon e fibbia di sicurezza per prevenire rischi di strangolamento, lavabile anche in lavatrice a 30°C massimo con programmi brevi e senza centrifuga', 20, 7.50, 2, 'collare4.png', 'image/png', 1),
('Collare Gatto Antiparassitario', 'Collare Seresto antizecche e antipulci con protezione continua fino a 7-8 mesi, inodore e resistente a contatti occasionali con l’acqua', 20, 22.90, 2, 'collare5.png', 'image/png', 1),
('Dentalife Snack Dentale Salmone', 'Snack dentale Purina Dentalife da 40g al gusto salmone, aiuta a ridurre la formazione di tartaro nei gatti adulti grazie alla sua consistenza porosa e croccante', 20, 3.50, 2, 'dentalife1.png', 'image/png', 1),
('Dentalife Snack Dentale Pollo', 'Snack dentale Purina Dentalife da 40g al gusto pollo, aiuta a ridurre la formazione di tartaro nei gatti adulti grazie alla sua consistenza porosa e croccante', 20, 3.50, 2, 'dentalife2.png', 'image/png', 1),
('Felix Le Ghiottonerie Junior', '10 bustine Purina Felix da 85g con teneri bocconcini di manzo e pollo in gelatina, adatto a gattini dai 2 ai 12 mesi per sostenere lo sviluppo di muscoli, ossa e denti sani', 20, 5.90, 2, 'felix1.png', 'image/png', 1),
('Felix Le Ghiottonerie Preferite', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di manzo e pollo oppure salmone e tonno, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix2.png', 'image/png', 1),
('Felix Le Ghiottonerie Varietà', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di platessa e tonno oppure coniglio e pollo, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix3.png', 'image/png', 1),
('Felix Le Ghiottonerie Verdure', '10 bustine Purina Felix da 85g con teneri bocconcini in gelatina di manzo e carote oppure pollo e pomodoro, ricchi di vitamine e minerali senza coloranti', 20, 5.90, 2, 'felix4.png', 'image/png', 1),
('Gioco Gatto Piume', 'Giocattolo Zolux Ethi’Cat realizzato con materiale riciclato e naturale, ideale per stimolare l’istinto predatorio e favorire l’esercizio fisico del proprio gatto', 20, 2.50, 2, 'gioco1.png', 'image/png', 1),
('Gioco Gatto Laser', 'Giocattolo interattivo Zolux Enjoy Laser per gatti, con un fascio di luce rossa per stimolare l’attività felina e dotato di un pratico portachiavi', 20, 4.90, 2, 'gioco2.png', 'image/png', 1),
('Gioco Gatto Topolino', 'Morbido topolino giocattolo in peluche, dotato di una lunga coda con un pon pon per attirare l’attenzione del proprio gatto grazie anche alla presenza di erba gatta al suo interno', 20, 2.50, 2, 'gioco3.png', 'image/png', 1),
('Guanto Leva Pelo Lovedì', 'Set composto da due guanti con cinturino regolabile e piccoli puntini in silicone che catturano peli, sporco e polvere non solo dal proprio animale ma anche da divani, letti e tappeti', 20, 6.50, 2, 'pulizia1.png', 'image/png', 1),
('Spazzola Lovedì', 'Morbida spazzola per gatti con setole in nylon per lucidare e lisciare tutti i tipi di pelo, dotata di un’impugnatura ergonomica e antiscivolo per una presa confortevole durante la toelettatura', 20, 7.50, 2, 'pulizia2.png', 'image/png', 1),
('Taglia Unghie Lovedì', 'Forbicine per gatti di taglia S con lame in acciaio inossidabile per garantire un taglio netto e preciso, facilitato da una comoda tacca di sicurezza in modo da non accorciare troppo l’unghia', 20, 5.90, 2, 'pulizia3.png', 'image/png', 1),
('Cardatore Lovedì', 'Cardatore per gatti di taglia S con setole in acciaio per districare il sottopelo, rimuovendo i peli morti e prevenendo la formazione di nodi', 20, 7.90, 2, 'pulizia4.png', 'image/png', 1),
('Tiragraffi Torre Multipiano', 'Tiragraffi beige in sisal di misure 103x71x49 cm che comprende una comoda cuccia, una piccola amaca e una pallina in peluche appesa', 20, 39.90, 2, 'tiragraffi1.png', 'image/png', 1),
('Tiragraffi Palo con Labirinto', 'Colonna tiragraffi in robusto sisal di misure 43,5x30 cm, dotata di una base con binari per far scorrere le palline e un pendente in legno appeso con una piuma', 20, 9.90, 2, 'tiragraffi2.png', 'image/png', 1),
('Trasportino Rigido Grigio', 'Trasportino per gatti fino a 8kg in plastica resistente con porta di metallo, conforme agli standard IATA per il trasporto aereo e dotato di una comoda lettiera perfetta per affrontare lunghi viaggi', 20, 32.90, 2, 'trasportino1.png', 'image/png', 1),
('Trasportino Nero con Borsa Imbottita', 'Trasportino in poliestere di dimensioni 29x31x49 cm adatto sia in casa che in viaggio, dotato di cuccia interna estraibile in peluche e varie aperture frontali, laterali e superiori', 20, 35.90, 2, 'trasportino2.png', 'image/png', 1),
('Whiskas Adult Pollo', 'Confezione da 1,4 kg di crocchette Whiskas al pollo per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas1.png', 'image/png', 1),
('Whiskas Junior Pollo', 'Confezione da 1,4 kg di crocchette Whiskas al pollo per gattini in crescita di età compresa tra 2 e 12 mesi, facili da digerire e con nutrienti essenziali per lo sviluppo', 20, 6.60, 2, 'whiskas2.png', 'image/png', 1),
('Whiskas Adult Tonno', 'Confezione da 1,4 kg di crocchette Whiskas al tonno per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas3.png', 'image/png', 1),
('Whiskas Adult Manzo', 'Confezione da 1,4 kg di crocchette Whiskas al manzo per gatti adulti con vitamina E, taurina e minerali per supportare il sistema immunitario e favorire il benessere del cuore e del tratto urinario', 20, 6.70, 2, 'whiskas4.png', 'image/png', 1);


INSERT INTO prodotto (Nome, Descrizione, Disponibilita, Prezzo, ID_Categoria, immagine, mime_type, attivo) VALUES
('Ciotola Cane Doppia', 'Set ciotole in acciaio inox rimovibili e lavabili in lavastoviglie, con supporto in legno e decorazioni con motivo a zampetta di cane', 20, 15.90, 1, 'img/cani/ciotola1.jpg', 'image/jpg', 1),
('Ciotola Cane Food', 'Ciotola in acciaio inox lavabile in lavastoviglie con base antiscivolo e decoro monocolore con frase simpatica', 20,  10.50, 1, 'img/cani/ciotola2.jpg', 'image/jpg', 1),
('Ciotola Cani Anti-Voracità', 'Ciotola in plastica dura lavabile in lavastoviglie con base antiscivolo e irregolarità al suo interno per rallentare l''assunzione di cibo', 20, 10.90, 1, 'img/cani/ciotola3.jpg', 'image/jpg',1),
('Collare Cane in Tessuto', 'Collare blu, in tessuto, regolabile, con gancio e medaglietta in metallo', 20, 20.00, 1, 'img/cani/collare1.jpg', 'image/jpg', 1),
('Collare Cane in Tessuto', 'Collare lilla, in tessuto, regolabile, con gancio e medaglietta in metallo', 20, 20.00, 1, 'img/cani/collare2.jpg', 'image/jpg', 1),
('Collare Cane in Tessuto', 'Collare rosso, in tessuto, regolabile, con gancio e medaglietta in metallo', 20, 20.00, 1, 'img/cani/collare3.jpg', 'image/jpg', 1),
('Collare Cane in Tessuto', 'Collare verde, in tessuto, regolabile, con gancio e medaglietta in metallo', 20, 20.00, 1, 'img/cani/collare4.jpg', 'image/jpg', 1),
('Cravatta Cane Elegante', 'Collare con cravatta nera classica e colletti di camicia bianchi, regolabile', 20, 18.90, 1, 'img/cani/cravatta.jpg', 'image/jpg', 1),
('Fiocco Cane Elegante', 'Collare con fiocco rosa in velluto, regolabile, con gancio e medaglietta in metallo', 20, 20.00, 1, 'img/cani/fiocco.jpg', 'image/jpg', 1),
('Papillon Cane Elegante', 'Collare con papillon classico nero, regolabile e con fibia in metallo', 20, 18.90, 1, 'img/cani/papillon.jpg', 'image/jpg', 1),
('Collare Seresto Antipulci Cani', 'Collare Seresto antipulci per cani di taglia grande di peso superiore agli 8kg. Fino a 7-8 mesi di protezione', 20, 28.99, 1, 'img/cani/seresto1.jpg', 'image/jpg', 1),
('Collare Seresto Antipulci Cani', 'Collare Seresto antipulci per cani di taglia medio-piccola di peso non superiore ai 8kg. Fino a 7-8 mesi di protezione ', 20, 28.99, 1, 'img/cani/seresto2.jpg', 'image/jpg', 1),
('Gocce Antipulci Advantix Cani', 'Gocce antipulci advantix per cani di taglia grande di peso superiore ai 25kg', 20, 24.99, 1, 'img/cani/advantix.jpg', 'image/jpg', 1),
('Spazzola Cani Rimozione Facile', 'Spazzola per cani con presa in gomma, dentini in ferro e pulsante per facilitare la rimozione dei peli raccolti', 20, 7.99, 1, 'img/cani/spazzola1.jpg', 'image/jpg', 1),
('Spazzola Cani', 'Spazzola per cani con presa in plastica e sezione antiscivolo, dentini in ferro. In dotazione con pettine', 20, 7.50, 1, 'img/cani/spazzola2.jpg', 'image/jpg', 1),
('Spazzola Cani Pro', 'Spazzola per cani con presa in gomma, denti in ferro. Da utilizzare preferibilmente su cani di taglia grande a pelo medio-lungo', 20, 9.90, 1, 'img/cani/spazzola3.jpg', 'image/jpg', 1),
('Crocchette Cani Monge gusto Agnello', 'Pacco di crocchette Monge da 2,5 kg, gusto agnello e riso, adatto a tutti i tipi di cane. Per cuccioli e junior', 20, 40.99, 1, 'img/cani/monge1.jpg', 'image/jpg', 1),
('Crocchette Cani Monge gusto Trota', 'Pacco di crocchette Monge da 2,5 kg, gusto trota con riso e patate, adatto a tutti i tipi di cane adulti', 20, 40.99, 1, 'img/cani/monge2.jpg', 'image/jpg', 1),
('Crocchette Cani Monge gusto Maiale', 'Pacco di crocchette Monge da 12 kg, gusto maiale con riso e patate, adatto a tutti i tipi di cane adulti', 20, 40.99, 1, 'img/cani/monge3.jpg', 'image/jpg', 1),
('Cibo Cani Monge gusto Maiale', 'Scatoletta di cibo per cani Monge gusto maiale. Adatto a tutti i tipi di cane adulti', 20, 15.90, 1,  'img/cani/monge4.jpg', 'image/jpg', 1),
('Cibo Cani Monge gusto Anatra', 'Scatoletta di cibo per cani Monge gusto anatra. Adatto a tutti i tipi di cane adulti', 20, 15.90, 1,  'img/cani/monge5.jpg', 'image/jpg', 1),
('Cibo Cani Monge gusto Agnello', 'Scatoletta di cibo per cani Monge gusto agnello. Adatto a tutti i tipi di cane adulti', 20, 15.90, 1,  'img/cani/monge6.jpg', 'image/jpg', 1),
('Cibo Cani Monge gusto Pollo', 'Scatoletta di cibo per cani Monge gusto pollo. Adatto a tutti i tipi di cane adulti', 20, 15.90, 1,  'img/cani/monge7.jpg', 'image/jpg', 1),
('Cibo Cani Purina Pro Plan Gastrointestinal', 'Scatoletta di cibo per cani in mousse Purina Pro Plan per cani che soffrono di problemi gastrointestinali', 20, 3.45, 1, 'img/cani/purina1.jpg', 'image/jpg', 1),
('Cibo Cani Purina Pro Plan Hypoallergenic', 'Scatoletta di cibo per cani in mousse Purina Pro Plan ipoallergenica', 20, 3.45, 1, 'img/cani/purina2.jpg', 'image/jpg', 1),
('Cibo Cani Purina Pro Plan Renal Function', 'Scatoletta di cibo per cani in mousse Purina Pro Plan per cani che soffrono di problemi renali', 20, 3.45, 1, 'img/cani/purina3.jpg', 'image/jpg', 1),
('Crocchette Cani Royal Canin XL', 'Pacco di crocchette per cani Royal Canin per cani adulti di peso superiore ai 45 kg. Confezione da 15kg' , 20, 75.00, 1, 'img/cani/royal1.jpg', 'image/jpg', 1),
('Crocchette Cani Royal Canin M', 'Pacco di crocchette per cani Royal Canin per cani adulti di peso tra gli 11 e i 25 kg. Confezione da 15kg' , 20, 75.00, 1, 'img/cani/royal2.jpg', 'image/jpg', 1),
('Crocchette Cani Royal Canin S', 'Pacco di crocchette per cani Royal Canin per cani adulti di peso non superiore ai 10 kg. Confezione da 15kg' , 20, 75.00, 1, 'img/cani/royal3.jpg', 'image/jpg', 1),
('Crocchette Cani Royal Canin L', 'Pacco di crocchette per cani Royal Canin per cani adulti di peso tra i 26 e i 44kg. Confezione da 15kg' , 20, 75.00, 1, 'img/cani/royal4.jpg', 'image/jpg', 1),
('Pupazzo Procione Cani', 'Gioco per cani. Pupazzo di procione con squicker integrato. Adatto anche a giochi di forza' , 20, 15.30, 1, 'img/cani/gioco1.jpg', 'image/jpg', 1),
('Set Palline Cani', 'Set di 4 palline da gioco per cani. Palline di diverse forme con facce disegnate, in gomma, con squicker integrato' , 20, 17.00, 1, 'img/cani/gioco2.jpg', 'image/jpg', 1),
('Osso Rumoroso Cani', 'Gioco per cani. Osso di gomma bianco antistress, con scquicker integrato. Adatto ai cuccioli che stanno sviluppando i primi denti', 20, 17.00, 1, 'img/cani/gioco3.jpg', 'image/jpg', 1),
('Corda Resistente Cani', 'Gioco per cani. Corda con nodo alle estremità per giochi di forza ', 20, 12.99, 1, 'img/cani/gioco4.jpg', 'image/jpg', 1);